import { Chat } from "./components";
import Providers from "./components/Providers";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <Providers>
        <body>
          {children}
          <Chat />
        </body>
      </Providers>
    </html>
  );
}
